# HLint configuration file
##########################

- functions:
  - {name: head, within: []} # head can only appear in no modules
  - {name: tail, within: []} 
  - {name: Maybe.fromJust, within: []} 

- ignore: {name: "Use head"}
- ignore: {name: "Use guards"}
- ignore: {name: "Use lambda-case"}
- ignore: {name: "Use $>"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use product"}
- ignore: {name: "Use sum"}
- ignore: {name: "Use mconcat"}
- ignore: {name: "Use list literal"}
- ignore: {name: "Reduce duplication"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Redundant lambda"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Replace case with fromMaybe"}
- ignore: {name: "Use mconcat"}
- ignore: {name: "Monoid law, left identity"}
- ignore: {name: "Use ||"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Use Control.Monad.void"}
